### ISSUE TITLE
Attach issues to scripts and code

### ISSUE THREAD

**Issue by soniamitchell** [FAIRDataPipeline/rFDP#108]

**Comment by richardreeve** [comment]
Do we want to be able to attach issues to naked objects, like scripts, yaml files and code?

**Comment by soniamitchell** [comment]
This is the question..

**Comment by richardreeve** [comment]
Yes, sorry - just adding in the other bits so I remembered!

**Comment by richardreeve** [comment]
Yes, we want to be able to attach an issue to the `whole_object` object component associated with a "naked" object like scripts, yaml files and code. Not sure how to integrate that with the `raise_issue()` command?
