### ISSUE TITLE
allow users to read (and write) multiple versions of a component from the same config

### ISSUE THREAD

**Issue by soniamitchell** [FAIRDataPipeline/rFDP#116]

**Comment by soniamitchell** [comment]
Posted something in Zulip suggesting a change to the working config format. Since for a data product absent from the registry, requires the second writing of the data product to read the config file and recognise the presence of a potential first writing, and therefore needs to check the `data_product` field both within and outside of the `use` block. Determining this information multiple times seems redundant.

**Comment by soniamitchell** [comment]
waiting on working config formatting decisions.

**Comment by richardreeve** [comment]
There is a bit of redundant work, but I think the working config.yaml will be easier to read with less duplication in it. We'll see what people say at 3pm.

**Comment by richardreeve** [comment]
I think the only remaining change here is to allow the default state of `public:` to be read from the `run_metadata:` block and used if one is not provided in `use:`?

**Comment by soniamitchell** [comment]
I'd intended to allow the user to add `public:` outside of `use:`, for ease of writing reasons. Perhaps we should allow both, for people that like to write things in `use:`?

**Comment by richardreeve** [comment]
Sure. Though we could say that the working config file will put everything that breaks the default (like adding in `public:`) into the `use:` block, so the DPAPI code only has to look in one place?

**Comment by soniamitchell** [comment]
Yep, I've made it so that anything the CLI writes is put in 'use:'. I'm happy for `fair run` to move `public` to the `use` block, as it already does with `version`.

Though I'd suggest the default for the user-written file be outside of `use:` for simplicity. Since currently, user-written files rarely contain `use:` (only with aliases).

We'll need to add this to the documentation.

**Comment by richardreeve** [comment]
Sure, I don't have a strong feeling either way, so put what you think makes most sense to you.
