### ISSUE TITLE
`delete_if_duplicate` argument for incremented versions in `finalise()`

### ISSUE THREAD

**Issue by soniamitchell** [FAIRDataPipeline/rFDP#118]
If an incremented data product has the same hash as a previous version, remove it from the registry and data store when this argument is true.

**Comment by richardreeve** [comment]
Should this be in `finalise()` or in `write_*()` to allow finer grained work? Also, if the whole code run produces no output, should there be a `delete_if_empty` argument to delete the code run completely?

**Comment by soniamitchell** [comment]
Could do both? I preferred `finalise()` because then you'd only need to set the argument in one place.. but finer grained work makes sense.

**Comment by soniamitchell** [comment]
Raised issue #126

**Comment by richardreeve** [comment]
On reflection, I prefer your all-or-nothing approach and put the `delete_if_duplicate` into `finalise()` for now at least.

**Comment by soniamitchell** [comment]
remember to delete the file from the data store
