### ISSUE TITLE
`delete_if_empty` argument in `finalise()` to delete code runs that produce no output

### ISSUE THREAD

**Issue by soniamitchell** [FAIRDataPipeline/rFDP#126]
* would this be `TRUE` by default?
* if the code run contains a read and `raise_issue()` does that count as an output?

**Comment by richardreeve** [comment]
> * if the code run contains a read and `raise_issue()` does that count as an output?
Definitely. I think that relates to the main case where we would want the `delete_if_empty` to be false - something doing some checking that succeeds (i.e. there is no problem) probably still wants to be recorded to show the check happened.

**Comment by richardreeve** [comment]
I think this is false by default, so if you run some code it always does something unless you specifically tell it not to!

**Comment by soniamitchell** [comment]
Waiting on DELETE method being enabled on CodeRun table.
