### ISSUE TITLE
Fix intermittent issue with test:

### ISSUE THREAD

**Issue by RyanJField** [FAIRDataPipeline/rFDP#23]
Age class 1 of 1; datazone 25 of 25...── 1. Failure: convert2grid() distributes integers broadly equally when there ar
all(rank_correlation < 0.15) isn't true.

**Comment by RyanJField** [comment]
I intermittently get this error, it has also occurred on continuous integration

**Comment by soniamitchell** [comment]
fixed scoping on functions, the error should be fixed now

**Comment by soniamitchell** [comment]
The error wasn't fixed. It's an intermittent error in `convert2grid() distributes integers broadly equally when there are ties`, specifically in `testthat::expect_true(all(rank_correlation < 0.15))`. I've set a seed to 123 to stem the problem until someone can look at it.

**Comment by Nardus** [comment]
That test is unfortunately somewhat prone to false positives. Setting the random seed might be the best solution for now (unless you're willing to accept a higher cut-off), since I can't currently think of a more robust method for testing this.

**Comment by soniamitchell** [comment]
setting the seed didn't fix the problem in the end... so we've been skipping the test (and avoiding the problem)

**Comment by soniamitchell** [comment]
moved function to SCRCdata
