### ISSUE TITLE
Implement `cache` field

### ISSUE THREAD

**Issue by soniamitchell** [FAIRDataPipeline/rFDP#98]

**Comment by richardreeve** [comment]
I'm not sure this is necessary is it? It only occurs in a `register:` block, doesn't it? And `fair run` will convert this into a `read:` block, and the `cache` will just be in the registry as the StorageLocation where the file is stored.

**Comment by soniamitchell** [comment]
I was under the impression you wanted a cached option for read and write? I haven’t touched the cache field yet so any guidance would be useful 👍
